export const regiones = {
	'red-blue': 'kanto',
	'gold-silver': 'johto',
	'ruby-sapphire': 'hoenn',
	emerald: 'hoenn',
	'pearl-diamond': 'sinnoh',
	platinum: 'sinnoh',
	'black-white': 'teselia',
	'black-2-white-2': 'teselia',
	'x-y': 'kalos',
	'sun-moon': 'alola',
	'ultra-sun-ultra-moon': 'alola',
	'sword-shield': 'galar',
	'legends-arceus': 'hisui',
	'scarlet-violet': 'paldea',
	'the-teal-mask': 'noroteo',
	'the-indigo-disk': 'paldea',
};
